### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by Thaksharapaka** [IP-2023/frontend#1]
(node:34428) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by Thaksharapaka** [comment]
node:events:490
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at Server.listen (node:net:1876:7)
    at Function.listen (c:\Users\Thakshara\Downloads\reddit-story-tiktok-bot-main\reddit-story-tiktok-bot-main\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (c:\Users\Thakshara\Downloads\reddit-story-tiktok-bot-main\reddit-story-tiktok-bot-main\app.js:67:5)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1767:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 8080
}

Node.js v19.7.0

[Done] exited with code=1 in 1.758 seconds
